const LocalizeText = {
    "en-US": {
        Bot: "Bot",
        Process: "Process",
        WhatsApp: "WhatsApp",
        SMS: "SMS",
        RCS: "RCS",
        MyApps: "My Apps",
        MyUsers: "My Users",
        SecondaryERPs: "Secondary ERPs",
        Rates: "Rates",
        PrivilegesAndRoles: "Privileges & Roles",
        Names: "Names",
        NewSecondaryERP: "New Secondary ERP",
        Proceed: "Proceed",
        IsLoggedInSuccessfullyAs: "is logged-in successfully as",
        EnterWhitelistedIPs: "Enter Whitelisted IPs",
        Owner: "Owner",
        Admin: "Admin",
        User: "User",
        ConsumerUnitName: "Consumer Unit Name",
        ConsumerUnits: "Consumer Units",
        AddAPIKey: "Add API key",
        LinkWABAS: "Link WABAS",
        LinkUsers: "Link Users",
        Bills: "Bills",
        NewWabaId: "New Waba Id",
        NewConsumerUnit: "New Consumer Unit",
        WABAS: "WABAS",
        Integrations: "Integrations",
        AddNewIntegration: "Add New Integration",
        Channel: "Channel",
        IntegrationType: "Integration Type",
        BrandName: "Brand Name",
        Brands: "Brands",
        ViewLinkedBots: "View Linked Bots",
        BotName: "Bot Name",
        SenderIDs: "Sender IDs",
        EntityID: "Entity ID",
        Add: "Add",
        View: "View",
    },
    "fr-FR": {
        Bot: "Bot",
        Process: "Process",
        WhatsApp: "WhatsApp",
        SMS: "SMS",
        RCS: "RCS",
        MyApp: "My Apps",
        MyUsers: "My Users",
        SecondaryERPs: "Secondary ERPs",
        Rates: "Rates",
        PrivilegesAndRoles: "Privileges & Roles",
        Names: "Names",
        NewSecondaryERP: "New Secondary ERP",
        Proceed: "Proceed",
        IsLoggedInSuccessfullyAs: "is logged-in successfully as",
        EnterWhitelistedIPs: "Enter Whitelisted IPs",
        Owner: "Owner",
        Admin: "Admin",
        User: "User",
        ConsumerUnitName: "Consumer Unit Name",
        ConsumerUnits: "Consumer Units",
        AdAPIkey: "Add API key",
        LinkWABAS: "Link WABAS",
        LinkUsers: "Link Users",
    },
    "ar-SA": {
        // Bot: 'بوت',
        Process: "عملية",
        // WhatsApp: 'WhatsApp',
        // SMS: 'SMS',
        RCS: "RCS",
        MyApps: "تطبيقاتي",
        MyUsers: "المستخدمين الخاص بي",
        SecondaryERPs: "Secondary ERPs",
        // Rates: 'Rates',
        // PrivilegesAndRoles: 'Privileges & Roles',
        Names: "Names",
        NewSecondaryERP: "New Secondary ERP",
        Proceed: "Proceed",
        IsLoggedInSuccessfullyAs: "is logged-in successfully as",
        EnterWhitelistedIPs: "Enter Whitelisted IPs",
        Owner: "مالك",
        Admin: "مسؤل",
        User: "مستخدم",
        ConsumerUnitName: "Consumer Unit Name",
        ConsumerUnits: "Consumer Units",
        AddAPIKey: "Add API key",
        LinkWABAS: "Link WABAS",
        LinkUsers: "Link Users",
        TechSupport: "الدعم الفني",
        BillingSupport: "دعم الفواتير",
        SalesSupport: "دعم المبيعات",
        Username: "اسم المستخدم",
        PhoneNumber: "رقم التليفون",
        Roles: "الأدوار",
        SubRoles: "الأدوار الفرعية",
        Delete: "يمسح",
        NewUser: "مستخدم جديد",
        Registries: "السجلات",
        AppName: "اسم التطبيق",
        PrivilegesAndRoles: "الامتيازات والأدوار",
        Rates: "الأسعار",
        Settings: "إعدادات",
        Bot: "بوت",
        WhatsApp: "واتساب",
        SMS: "رسالة قصيرة",
        BillingDetails: "تفاصيل الفواتير",
        Consumption: "استهلاك",
        Bills: "فواتير",
        Apps: "تطبيقات",
        NewRegistry: "سجل جديد",
        LogOut: "تسجيل الخروج",
    },
};
let currentLocale = "en-US";
// let currentLocale = "ar-SA";
export let currentDir = "ltr";
// export let currentDir = "rtl";

export const displayLocalizeText = key => {
    return LocalizeText[currentLocale][key] ? LocalizeText[currentLocale][key] : key;
};

export const setCurrentLocale = newLocale => {
    currentLocale = newLocale;
};
