export const UserProfileColors = {
    A: "#fee2e2",
    B: "#ffedd5",
    C: "#fef3c7",
    D: "#fef9c3",
    E: "#fef9c3",
    F: "#ecfccb",
    G: "#dcfce7",
    H: "#d1fae5",
    I: "#ccfbf1",
    J: "#cffafe",
    K: "#e0f2fe",
    L: "#dbeafe",
    M: "#e0e7ff",
    N: "#ede9fe",
    O: "#fae8ff",
    P: "#fce7f3",
    Q: "#fca5a5",
    R: "#fde68a",
    S: "#d9f99d",
    T: "#a7f3d0",
    U: "#a5f3fc",
    V: "#bfdbfe",
    W: "#ddd6fe",
    X: "#fbcfe8",
    Y: "#fda4af",
    Z: "#f472b6",
};
